# Generated by Django 5.0.4 on 2024-04-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_description_job_experience_job_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
